- README.md
- src/index.ts
- src/utils.ts
- test/fixtures/app/tshelper.js
- test/index.test.ts
`class.generator`
[Egg 兼容] `caseStyle` 参数支持函数传入，用于自定义挂载节点名
fixs #18
> caseStyle option add function support

- src/generators/class.ts
- src/index.ts
- src/watcher.ts
- test/fixtures/real/typings/app/custom/index.d.ts
> fix: ignore watcher initial

- package.json
- src/register.ts
- test/register.test.ts
> fix: register should use env instead of file

- src/register.ts
> fix: fix spawn eagain

- README.md
- README.zh-CN.md
- src/cmd/clean.ts
- src/utils.ts
- test/cmd/clean.test.ts
- test/fixtures/app9/app/app/testtsx.tsx
- test/fixtures/app9/app/testtsx.tsx
- test/fixtures/app9/testtsx.tsx
- test/fixtures/app9/tsconfig.json
- test/utils.test.ts
> feat: clean js file while it has the same name tsx file too

- .gitignore
- package.json
- src/config.ts
- src/index.ts
- src/scripts/eggInfo.ts
- src/utils.ts
- test/utils.test.ts
- tslint.json
> feat: speed up booting

- package.json
- src/bin.ts
- src/cmd/init.ts
- src/config.ts
- src/index.ts
- src/utils.ts
- test/cmd/init.test.ts
- test/fixtures/app2/config/plugin.local.ts
- test/fixtures/app4/config/plugin.ts
- test/fixtures/app4/node_modules
- test/fixtures/app4/node_modules/egg-sequelize/package.json
- test/fixtures/app4/package.json
- test/generators/class.test.ts
- test/generators/plugin.test.ts
- test/index.test.ts
- test/utils.test.ts
- test/utils.ts
> fix: clean files before startup & model compatible

- package.json
- src/register.ts
- src/utils.ts
> fix: should clean file more intelligent

- package.json
> fix: downgrade ts-node

- src/generators/class.ts
> fix: same name dir and file

- src/index.ts
- test/generators/class.test.ts
deps on https://github.com/eggjs/egg-sequelize/pull/73
> feat: remove compatible for egg-sequelize

- src/generators/config.ts
- src/generators/extend.ts
fix duplicate declaration error.
> fix: duplicate declaration

- src/generators/config.ts
- src/index.ts
- src/utils.ts
- src/watcher.ts
- test/fixtures/app/config/config.default.ts
- test/fixtures/real-js/config/config.local.js
- test/fixtures/real/tsconfig-base.json
- test/fixtures/real/tsconfig.json
- test/generators/config.test.ts
- test/index.test.ts
- test/utils.test.ts
- test/utils.ts
> fix: fix config types error

- src/generators/class.ts
- src/index.ts
- test/fixtures/app/app/controller/multi-parent.ts
- test/fixtures/app/app/controller/multi-parent/sub.ts
- test/fixtures/app/app/controller/multi/sub.ts
- test/generators/class.test.ts
优化多级目录生成的声明文件。
```javascript
interface IController {
home: ExportHome;
// add Intersection Types
parent: ExportParent & {
sub: ExportParentSub;
}
}
```
> feat: support multi-level directory with intersection types

- src/index.ts
- test/bin.test.ts
- test/index.test.ts
> fix: service is method

- src/register.ts
> fix: autoRemoveJs should works in register

- .appveyor.yml
- .travis.yml
- package.json
- src/register.ts
- src/watcher.ts
> fix: remove ts args checking

- src/generators/custom.ts
- src/generators/plugin.ts
- src/index.ts
- src/utils.ts
- test/generators/plugin.test.ts
- test/index.test.ts
- test/utils.test.ts
- test/utils.ts
> feat: support custom loader

- package.json
- src/generator.ts
- src/generators/auto.ts
- src/generators/base.ts
- src/generators/class.ts
- src/generators/config.ts
- src/generators/custom.ts
- src/generators/egg.ts
- src/generators/extend.ts
- src/generators/function.ts
- src/generators/object.ts
- src/generators/plugin.ts
- src/index.ts
- src/utils.ts
- src/watcher.ts
- test/generator.test.ts
- test/generators/extend.test.ts
- test/index.test.ts
- tsconfig.json
> feat: support class style generator

- package.json
- src/utils.ts
- test/fixtures/test-tsconfig/tsconfig.json
- test/utils.test.ts
> fix: load tsconfig with extends

- package.json
> fix: should not use exports

- src/register.ts
> fix: ETS_REGISTER_PID should not relate watch mode

- src/utils.ts
> fix: clean ignore tegg .sff dir

- package.json
- src/generators/class.ts
- src/generators/extend.ts
- src/register.ts
- src/watcher.ts
- test/index.test.ts
- test/register.test.ts
https://github.com/eggjs/egg/issues/5087
> feat: remove debug deps
